name: CICD - Branch
on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:
jobs:
  reuse:
    uses: devops-learning-projects/roboshop-github-actions/.github/workflows/cicd-branch.yml@main